name: Run K6 Load Tests

on:
  pull_request:
    branches:
      - main  # Este workflow será disparado quando um PR for aberto/atualizado para a branch main

jobs:
  run-k6-tests:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer checkout do código
      - name: Check out repository
        uses: actions/checkout@v4

      # Passo 2: Instalar o K6
      - name: Install K6
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/grafana/k6/releases/download/v0.42.0/k6-v0.42.0-linux-amd64.deb
          sudo dpkg -i k6-v0.42.0-linux-amd64.deb
          sudo apt-get install -f  # Corrigir possíveis dependências

      # Passo 3: Executar o teste K6 e gerar o relatório HTML
      - name: Run K6 load tests and generate HTML report
        run: |
          k6 run load_tests.js --summary-export=summary.json
          k6 run load_tests.js --out html=result.html

      # Passo 4: Salvar o relatório HTML como artefato
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: k6-report
          path: result.html
